### ISSUE TITLE
Fatal Error on plugin activation

### ISSUE THREAD

**Issue by bobsawyer** [cferdinandi/gmt-wordpress-for-web-apps#103]
- Fresh install of WordPress 4.7
- Current version of GMT WFWA plugin (vers. 8.0.1)
- Plugin installed: tried via .zip upload and via unzipped directory upload via FTP
- Theme: tried default themes Twenty-Fifteen, Twenty-Sixteen, and Twenty-Seventeen with same result.
- Other plugins (tried activated and deactivated): WordFence Security
- Upon activation, I get the following: "Plugin could not be activated because it triggered a fatal error."
`Fatal error: Can't use function return value in write context in /home/site/public_html/wp-content/plugins/gmt-wordpress-for-web-apps-master/includes/helpers.php on line 149`

**Comment by cferdinandi** [comment]
Hi there - First off, thank you so much for the detailed debugging information. This was really helpful in tracking down the issue.

Line 149 is an `if` statement that checks if a function returns true on `empty`. [From the PHP manual:](http://php.net/manual/en/function.empty.php#refsect1-function.empty-parameters)

> **Note:** Prior to PHP 5.5, `empty()` only supports variables; anything else will result in a parse error. In other words, the following will not work: `empty(trim($name))`. Instead, use `trim($name) == false`.

In this case, because I'm checking a function on `empty()`, it's throwing an error. 

This only affects PHP 5.5 and older, however. The latest version 5 release is 5.6 ([which support ends for in just days](http://php.net/supported-versions.php)), with the latest stable version being 7.x.

As such, if this is the cause of the problem, I don't see myself addressing it. 

Can you confirm what version of PHP you're running? Do you have the ability to update if running an older version?

**Comment by bobsawyer** [comment]
Ahhh! Good catch. Currently running 5.4. I updated to 7 (very easily
courtesy of Cpanel) and that solved the issue.

Thank you!

**Comment by cferdinandi** [comment]
Excellent. Thanks again, Bob! Happy Holidays!
